### PR TITLE
Lab benchmarks

### LINKED ISSUE #88: Lab handle multiple benchmarks

### PR DESCRIPTION
**Pull request by matblicher**
Closes #88 
Run multiple domains use :
Run multiple problems in same domain use , 

Examples:
--benchmarks '$HOME/.vs/P7/Data/Classical tracks/'"
--domain 'gripper/gripper_domain.pddl:Hanoi/hanoi.pddl'
--problem 'gripper/gripper_problem.pddl:Hanoi/pb1.pddl, Hanoi/pb2.pddl'

--benchmarks '$HOME/.vs/P7/Data/benchmarks/'
--domain 'gripper:trucks'
--problem 'prob01.pddl,prob02.pddl,prob09.pddl:p03.pddl'

### CODE REVIEW

**Review by Cargo-BI — CHANGES_REQUESTED** [review]
Woops, wrong account...

**Review by kris701 — CHANGES_REQUESTED** [review]
Does not seem to work
Gives what looks like a parser error
`Unexplained error(s) in runs-00001-00100/00003: ['exitcode--11', 'run.err: 3.5-15: syntax error, unexpected predicates, expecting requirements\n3.18-21: syntax error, unexpected name, expecting define\nTraceback (most recent call last):\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../TranslatorParser.py", line 82, in <module>\n    parser.parse()\n  File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 213, in parse\n    with open(function.filename) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'downwardLog\'\nTraceback (most recent call last):\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../SingleSearchParser.py", line 174, in <module>\n    main()\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../SingleSearchParser.py", line 171, in main\n    parser.parse()\n  File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 213, in parse\n    with open(function.filename) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'downwardLog\'\nTraceback (most recent call last):\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../PlannerParser.py", line 106, in <module>\n    main()\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../PlannerParser.py", line 103, in main\n    parser.parse()\n  File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 215, in parse\n    function.function(content, self.props)\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../PlannerParser.py", line 9, in add_planner_memory\n    if props["coverage"]:\nKeyError: \'coverage\'\nTraceback (most recent call last):\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../AnytimeSearchParser.py", line 72, in <module>\n    main()\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../AnytimeSearchParser.py", line 69, in main\n    parser.parse()\n  File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 213, in parse\n    with open(function.filename) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'downwardLog\'\nTraceback (most recent call last):\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../P7LabParser.py", line 50, in <module>\n    parser.parse()\n  File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 215, in parse\n    function.function(content, self.props)\n  File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../P7LabParser.py", line 45, in get_times\n    props[stages[index]+"_ms"] = times[index]\nIndexError: list index out of range\n']`

**Comment by matblicher** [comment]
> Does not seem to work Gives what looks like a parser error `Unexplained error(s) in runs-00001-00100/00003: ['exitcode--11', 'run.err: 3.5-15: syntax error, unexpected predicates, expecting requirements\n3.18-21: syntax error, unexpected name, expecting define\nTraceback (most recent call last):\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../TranslatorParser.py", line 82, in <module>\n parser.parse()\n File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 213, in parse\n with open(function.filename) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'downwardLog\'\nTraceback (most recent call last):\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../SingleSearchParser.py", line 174, in <module>\n main()\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../SingleSearchParser.py", line 171, in main\n parser.parse()\n File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 213, in parse\n with open(function.filename) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'downwardLog\'\nTraceback (most recent call last):\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../PlannerParser.py", line 106, in <module>\n main()\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../PlannerParser.py", line 103, in main\n parser.parse()\n File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 215, in parse\n function.function(content, self.props)\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../PlannerParser.py", line 9, in add_planner_memory\n if props["coverage"]:\nKeyError: \'coverage\'\nTraceback (most recent call last):\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../AnytimeSearchParser.py", line 72, in <module>\n main()\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../AnytimeSearchParser.py", line 69, in main\n parser.parse()\n File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 213, in parse\n with open(function.filename) as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'downwardLog\'\nTraceback (most recent call last):\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../P7LabParser.py", line 50, in <module>\n parser.parse()\n File "/usr/local/lib/python3.10/dist-packages/lab/parser.py", line 215, in parse\n function.function(content, self.props)\n File "/root/.vs/P7/build/LabReport/runs-00001-00100/00003/../../P7LabParser.py", line 45, in get_times\n props[stages[index]+"_ms"] = times[index]\nIndexError: list index out of range\n']`

It is P7 in PDDLProblem.hpp that gives a segmentation fault. Try to run P7 without lab and the error appears. I think it is pddldriver.cc line 25 where the error comes from.

**Comment by kris701** [comment]
I doubt that its the PDDL Parser that all of a sudden fails.
There must be something with the new additions that fail

**Comment by kris701** [comment]
The benchmark files can run now.
However it is still complaining that it cant find `downwardLog`

**Comment by kris701** [comment]
Well, it technically runs
But its quite a big issue that it runs concurrently, but reads the same file

**Comment by matblicher** [comment]
For me it terminates and writes the report without gripper prob09.pddl. I think maybe the problem is hard and takes a long time. 
Each run gets its own folder in LabReport/runs-00001-00100 with all temp and log files.

**Review by kris701 — APPROVED** [review]
I guess it was just that one problem that took forever. Dont worry, that will be fixed in pr #110

**Pull request merged**
